relativeURLs = true
title = "Nitin Manocha"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]
googleAnalytics = "UA-90755326-1"

[params]
    shortbio = "Associate Director – Quality Assurance, Ex-Indian Navy"
    logo = "portrait.jpg"
    Twitter = "nitinmanocha"
    Orcid = "0000-0000-0000-0000"
    Email = "ernitin1989@gmail.com"
    Scholar = "citations?user=XXXXXX&hl=en"

